In [42]:
import numpy as np
import pandas as pd
import shutil


In [43]:
Alt = [1,1,0,1,1,0,0,0,0,1,0,1]
Bar = [0,0,1,0,0,1,1,0,1,1,0,1]
Fri = [0,0,0,1,1,0,0,0,1,1,0,1]
Hun = [1,1,0,1,0,1,0,1,0,1,0,1]
#full = 2, some= 1, none = 0
Pat = [1,2,1,2,2,1,0,1,2,2,0,2]
#$$$ = 2 , $$ =1 , $ = 0
Price = [2,0,0,0,2,1,0,1,0,2,0,0]
#Price = ['sss','s','s','s','sss','ss','s','ss','s','sss','s','s']
Rain = [0,0,0,1,0,1,1,1,1,0,0,0]
Res = [1,0,0,0,1,1,0,1,0,1,0,0]
#French =0 , Thai = 1 , Burger = 2 , Italian = 3
Type = [0,1,2,1,0,3,2,1,2,3,1,2]
# 0-10 = 0 , 10-30 = 1 , 30-60 = 2 , 60 > =3
Est = [0,2,0,1,3,0,0,0,3,1,0,2]
Goal = [1,0,1,1,0,1,0,1,0,0,0,1]

In [44]:
data = {'Alt':Alt,
        'Bar':Bar,
        'Fri':Fri,
        'Hun':Hun,
        'Pat':Pat,
        'Price':Price,
        'Rain':Rain,
        'res':Res,
        'Type':Type,
        'Est':Est,
        'Goal':Goal}
 
# Create DataFrame
df = pd.DataFrame(data)
 
# Print the output.
print(df)
#df.head(6)

    Alt  Bar  Fri  Hun  Pat  Price  Rain  res  Type  Est  Goal
0     1    0    0    1    1      2     0    1     0    0     1
1     1    0    0    1    2      0     0    0     1    2     0
2     0    1    0    0    1      0     0    0     2    0     1
3     1    0    1    1    2      0     1    0     1    1     1
4     1    0    1    0    2      2     0    1     0    3     0
5     0    1    0    1    1      1     1    1     3    0     1
6     0    1    0    0    0      0     1    0     2    0     0
7     0    0    0    1    1      1     1    1     1    0     1
8     0    1    1    0    2      0     1    0     2    3     0
9     1    1    1    1    2      2     0    1     3    1     0
10    0    0    0    0    0      0     0    0     1    0     0
11    1    1    1    1    2      0     0    0     2    2     1


In [45]:
col_names_diabetes = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness','Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']
shutil.copyfile("diabetes.csv", "diabetes_copy.csv")
data_diab = pd.read_csv("diabetes_copy.csv", skiprows=1, header=None, names=col_names_diabetes)
#data_diab.head(30)
data_diab = data_diab.astype({"BMI":'int', "DiabetesPedigreeFunction":'int'}) 
mindata =data_diab[data_diab.gt(0)].min(0)
maxdata = data_diab.max()
#find limitation
Pregnancies_min ,Pregnancies_max  = mindata['Pregnancies'],maxdata['Pregnancies']
Glucose_min ,Glucose_max  = mindata['Glucose'],maxdata['Glucose']
BloodPressure_min ,BloodPressure_max  = mindata['BloodPressure'],maxdata['BloodPressure']
SkinThickness_min ,SkinThickness_max  = mindata['SkinThickness'],maxdata['SkinThickness']
Insulin_min ,Insulin_max  = mindata['Insulin'],maxdata['Insulin']
BMI_min ,BMI_max  = mindata['BMI'],maxdata['BMI']
DiabetesPedigreeFunction_min ,DiabetesPedigreeFunction_max  = mindata['DiabetesPedigreeFunction'],maxdata['DiabetesPedigreeFunction']
Age_min ,Age_max  = mindata['Age'],maxdata['Age']
#list 
lst_Pregnancies = list(data_diab['Pregnancies'])
lst_Glucose = list(data_diab['Glucose'])
lst_BloodPressure = list(data_diab['BloodPressure'])
lst_SkinThickness = list(data_diab['SkinThickness'])
lst_Insulin = list(data_diab['Insulin'])
lst_BMI = list(data_diab['BMI'])
lst_DiabetesPedigreeFunction = list(data_diab['DiabetesPedigreeFunction'])
lst_Age = list(data_diab['Age'])






In [46]:
avg_Pregnancies = (Pregnancies_max - Pregnancies_min)/2
avg_Glucose = (Glucose_max - Glucose_min )/2
avg_BloodPressure = (BloodPressure_max - BloodPressure_min )/2
avg_SkinThickness = (SkinThickness_max - SkinThickness_min )/2
avg_Insulin = (Insulin_max - Insulin_min )/2
avg_BMI = (BMI_max - BMI_min )/2
avg_DiabetesPedigreeFunction = (DiabetesPedigreeFunction_max - DiabetesPedigreeFunction_min )/2
avg_Age = (Age_max - Age_min )/2
#['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness','Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']
data_diab["Pregnancies"] = data_diab["Pregnancies"].replace(to_replace=[x for x in lst_Pregnancies if x <= avg_Pregnancies ] , value = 0)
data_diab["Pregnancies"] = data_diab["Pregnancies"].replace(to_replace=[x for x in lst_Pregnancies if x > avg_Pregnancies ] , value = 1)
# print(data_diab['Pregnancies'])
data_diab["Glucose"] = data_diab["Glucose"].replace(to_replace=[x for x in lst_Glucose if x <= avg_Glucose ] , value = 0)
data_diab["Glucose"] = data_diab["Glucose"].replace(to_replace=[x for x in lst_Glucose if x > avg_Glucose ] , value = 1)
# print(data_diab['Glucose'])
data_diab["BloodPressure"] = data_diab["BloodPressure"].replace(to_replace=[x for x in lst_BloodPressure if x <= avg_BloodPressure ] , value = 0)
data_diab["BloodPressure"] = data_diab["BloodPressure"].replace(to_replace=[x for x in lst_BloodPressure if x > avg_BloodPressure ] , value = 1)
# print(data_diab['BloodPressure'])
data_diab["SkinThickness"] = data_diab["SkinThickness"].replace(to_replace=[x for x in lst_SkinThickness if x <= avg_SkinThickness] , value = 0)
data_diab["SkinThickness"] = data_diab["SkinThickness"].replace(to_replace=[x for x in lst_SkinThickness if x > avg_SkinThickness ] , value = 1)
# print(data_diab['SkinThickness'])
data_diab["Insulin"] = data_diab["Insulin"].replace(to_replace=[x for x in lst_Insulin if x <= avg_Insulin ] , value = 0)
data_diab["Insulin"] = data_diab["Insulin"].replace(to_replace=[x for x in lst_Insulin if x > avg_Insulin] , value = 1)
# print(data_diab['Insulin'])
data_diab["BMI"] = data_diab["BMI"].replace(to_replace=[x for x in lst_BMI if int(x) <= int(avg_BMI) ] , value = 0)
data_diab["BMI"] = data_diab["BMI"].replace(to_replace=[x for x in lst_BMI if int(x) > int(avg_BMI) ] , value = 1)
ls = list(data_diab["BMI"] )
print(ls)
# print(data_diab['BMI'])
data_diab["DiabetesPedigreeFunction"] = data_diab["DiabetesPedigreeFunction"].replace(to_replace=[x for x in lst_DiabetesPedigreeFunction if x <= avg_DiabetesPedigreeFunction ] , value = 0)
data_diab["DiabetesPedigreeFunction"] = data_diab["DiabetesPedigreeFunction"].replace(to_replace=[x for x in lst_DiabetesPedigreeFunction if x > avg_DiabetesPedigreeFunction ] , value = 1)
# print(data_diab['DiabetesPedigreeFunction'])
data_diab["Age"] = data_diab["Age"].replace(to_replace=[x for x in lst_Age if x <= avg_Age ] , value = 0)
data_diab["Age"] = data_diab["Age"].replace(to_replace=[x for x in lst_Age if x > avg_Age ] , value = 1)
# print(data_diab['Age'])

data_diab.head(25)

[1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
0             0        1              1              0        0    1   
1             0        1              1              0        0    1   
2             0        1              1              0        0    0   
3             0        1              1              0        0    1   
4             0        1              0              0        0    1   
5             0        1              1              0        0    1   
6             0        1              1              0        0    1   
7             1        1              0              0        0    1   
8             0        1              1              0        1    1   
9             0        1              1              0        0    0   
10            0        1              1              0        0    1   
11            1        1              1              0        0    1   
12            1        1              1              0        0    1   
13            0        1              1              0        1    1   
14            0        1              1              0        0    1   
15            0        1              0              0        0    1   
16            0        1              1              1        0    1   
17            0        1              1              0        0    1   
18            0        1              0              0        0    1   
19            0        1              1              0        0    1   
20            0        1              1              0        0    1   
21            0        1              1              0        0    1   
22            0        1              1              0        0    1   
23            1        1              1              0        0    1   
24            1        1              1              0        0    1   

    DiabetesPedigreeFunction  Age  Outcome  
0                          0    1        1  
1                          0    1        0  
2                          0    1        1  
3                          0    0        0  
4                          1    1        1  
5                          0    0        0  
6                          0    0        1  
7                          0    0        0  
8                          0    1        1  
9                          0    1        1  
10                         0    0        0  
11                         0    1        1  
12                         1    1        0  
13                         0    1        1  
14                         0    1        1  
15                         0    1        1  
16                         0    1        1  
17                         0    1        1  
18                         0    1        0  
19                         0    1        1  
20                         0    0        0  
21                         0    1        0  
22                         0    1        1  
23                         0    0        1  
24                         0    1        1

In [47]:
class Node():
    def __init__(self, feature_index=None, threshold=None, left=None, right=None, info_gain=None, value=None):
    #constructor 
        
        # which feature we are pointing to
        self.feature_index = feature_index
        self.threshold = threshold
        #move from parent node to child node
        self.left = left
        self.right = right
        #store IG by spliting
        self.info_gain = info_gain
        
        # for leaf node
        #just we need the value of leaf node
        self.value = value

In [48]:
class DecisionTreeClassifier():
    def __init__(self, min_samples_split=2, max_depth=2):
        #constructor
        
        # use to traverse in to tree
        self.root = None
        
        # stopping conditions
        #stopping criteria : some time tree is so big so u district the branch of tree 
        # if in a specific node min sample > num sample --> make that node, leaf
        # if in a specific node max depth > num depth --> make that node, leaf
        self.min_samples_split = min_samples_split
        self.max_depth = max_depth
        
    def build_tree(self, dataset, curr_depth=0):
        #data which one to train at first or test at the end 
        
        X, Y = dataset[:,:-1], dataset[:,-1]
        #for exp in restaurant num sample = 12 and num feature = 10 
        num_samples, num_features = np.shape(X)
        
        # split until stopping conditions are met
        if num_samples>=self.min_samples_split and curr_depth<=self.max_depth:
            # find the best split
            best_split = self.get_best_split(dataset, num_samples, num_features)
            # check if information gain is positive
            # if best_split["info_gain"] < 0.0001 :
            #   best_split["info_gain"] = 0.0
            try:
                best_split["info_gain"]
                #print("Yes")
            except NameError:
                print("Error: No value detected")
            print(best_split["info_gain"])
            if best_split["info_gain"]>0:
                # recur left
                left_subtree = self.build_tree(best_split["dataset_left"], curr_depth+1)
                # recur right
                right_subtree = self.build_tree(best_split["dataset_right"], curr_depth+1)
                # return decision node
                #calc the IG if IG is bigger , it  becomes the node 
                return Node(best_split["feature_index"], best_split["threshold"], 
                            left_subtree, right_subtree, best_split["info_gain"])
        
        # compute leaf node
        leaf_value = self.calculate_leaf_value(Y)
        # return leaf node
        return Node(value=leaf_value)
    
    def get_best_split(self, dataset, num_samples, num_features):
         #find which one is better to split
        
        # dictionary to store the best split
        #info of node we want to set
        best_split = {}
        #the bigger the IG is , it becomes the node so at fisrt we set IC to -inf
        max_info_gain = -float("inf")
        
        #for exp in restaurant traverse through Alt  Bar  Fri  Hun  Pat  Price etc ...  
        for feature_index in range(num_features):
              #check value of feature folan(by index) like : col 9 form dataset
            #   [0 0 2 2 0 1 0]
             # [[0 0 0 1 1 1 1 1 1 0 1]
              # [0 0 0 0 0 0 0 0 1 0 0]
              # [1 0 0 1 2 0 0 0 1 2 0]
              # [1 1 1 1 2 0 0 0 2 2 1]
              # [0 1 0 0 1 0 0 0 2 0 1]
              # [1 0 1 1 2 0 1 0 1 1 1]
              # [1 0 0 1 1 2 0 1 0 0 1]]
            feature_values = dataset[:, feature_index]
            #find unique value of a bove list sorted like : [0,1,2]
            possible_thresholds = np.unique(feature_values)
            # traverse the unique values
            for threshold in possible_thresholds:
                # get current split
                dataset_left, dataset_right = self.split(dataset, feature_index, threshold)
                # check if childs are not null
                if len(dataset_left)>0 and len(dataset_right)>0:
                    y, left_y, right_y = dataset[:, -1], dataset_left[:, -1], dataset_right[:, -1]
                    # compute information gain
                    curr_info_gain = self.information_gain(y, left_y, right_y, "gini")
                    # update the best split if needed
                    if curr_info_gain>max_info_gain:
                        best_split["feature_index"] = feature_index
                        best_split["threshold"] = threshold
                        best_split["dataset_left"] = dataset_left
                        best_split["dataset_right"] = dataset_right
                        best_split["info_gain"] = curr_info_gain
                        max_info_gain = curr_info_gain
                        
        # return best split
        #that means find best feature to get the node and how to split feature using threshold
        #like if we have 4 value how to splite the
        return best_split
    
    def split(self, dataset, feature_index, threshold):
        #find best way to split data
        
        dataset_left = np.array([row for row in dataset if row[feature_index]<=threshold])
        dataset_right = np.array([row for row in dataset if row[feature_index]>threshold])
        return dataset_left, dataset_right
    
    def information_gain(self, parent, l_child, r_child, mode="entropy"):
        # 2 way to calc IG :1- use gini index : 1 - sumation(p**2),
        # 2- use entropy : -sumation( p log2 p)
        
        weight_l = len(l_child) / len(parent)
        weight_r = len(r_child) / len(parent)
        if mode=="gini":
            gain = self.gini_index(parent) - (weight_l*self.gini_index(l_child) + weight_r*self.gini_index(r_child))
        else:
            gain = self.entropy(parent) - (weight_l*self.entropy(l_child) + weight_r*self.entropy(r_child))
        return gain
    
    def entropy(self, y):
        #calc entropy
        
        class_labels = np.unique(y)
        entropy = 0
        for cls in class_labels:
            p_cls = len(y[y == cls]) / len(y)
            entropy += -p_cls * np.log2(p_cls)
        return entropy
    
    def gini_index(self, y):
        #calc gini index
        
        class_labels = np.unique(y)
        gini = 0
        for cls in class_labels:
            p_cls = len(y[y == cls]) / len(y)
            gini += p_cls**2
        return 1 - gini
        
    def calculate_leaf_value(self, Y):
        #return which item duplicate more
        #most common lable
        #polarity value
        #id u dont want to continue search pick most common val
        
        Y = list(Y)
        #find which member of list duplicate more
        return max(Y, key=Y.count)
    
    def print_tree(self, tree=None, indent=" "):
        ''' function to print the tree '''
        
        if not tree:
            tree = self.root

        if tree.value is not None:
            print(tree.value)

        else:
            print("Xfeature num_"+str(tree.feature_index), "<----- best threshold", tree.threshold, "highest IG for this tree : ", tree.info_gain)
            print("%sleft:" % (indent), end="")
            self.print_tree(tree.left, indent + indent)
            print("%sright:" % (indent), end="")
            self.print_tree(tree.right, indent + indent)

    # def Inorder(root):
    #   if root:
    #       Inorder(root.left)
    #       print(root.val, end=" ")
    #       Inorder(root.right)

    def fit(self, X, Y):
        # concat val x & y to give it to build tree
        
        dataset = np.concatenate((X, Y), axis=1)
        self.root = self.build_tree(dataset)
    
    def predict(self, X):
        #this part is use for test mode 
        
        preditions = [self.make_prediction(x, self.root) for x in X]
        return preditions
    
    def make_prediction(self, x, tree):
        #this part is use for test mode 
        #we can calc how much accuracy our code(tree) have
        
        if tree.value!=None: return tree.value
        feature_val = x[tree.feature_index]
        if feature_val<=tree.threshold:
            return self.make_prediction(x, tree.left)
        else:
            return self.make_prediction(x, tree.right)

In [49]:
X = df.iloc[:, :-1].values
Y = df.iloc[:, -1].values.reshape(-1,1)
#get same split each time add random state
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=.3, random_state=11)
# print(X.shape)
# print(X_train)
# print(Y_train)
# dataset = np.concatenate((X_train, Y_train), axis=1)
# Xmamad, Ymamad = dataset[:,:-1], dataset[:,-1]
# print(Xmamad)
# Ymamad = list(Ymamad)
# print(max(Ymamad, key=Ymamad.count))

In [50]:
X = data_diab.iloc[:, :-1].values
Y = data_diab.iloc[:, -1].values.reshape(-1,1)
#get same split each time add random state
from sklearn.model_selection import train_test_split
X_train_diab, X_test_diab, Y_train_diab, Y_test_diab = train_test_split(X, Y, test_size=.4, random_state=41)

In [38]:
classifier = DecisionTreeClassifier(min_samples_split=2, max_depth=3)
classifier.fit(X_train,Y_train)
classifier.print_tree()

0.28125
0.0
0.125
0.0
0.5
Xfeature num_4 <----- best threshold 1 highest IG for this tree :  0.28125
 left:1
 right:Xfeature num_1 <----- best threshold 0 highest IG for this tree :  0.125
  left:0
  right:Xfeature num_5 <----- best threshold 0 highest IG for this tree :  0.5
    left:1
    right:0


In [51]:
classifier = DecisionTreeClassifier(min_samples_split=3, max_depth=3)
classifier.fit(X_train_diab,Y_train_diab)
classifier.print_tree()

0.033572874300662525
0.02322951967884429
0.00013023255813962575
0.0
5.2764183672039666e-05
0.017940038150619897
0.006513487976686272
0.02777777777777768
0.018227965877619212
0.0100173913043477
0.0061866300051556244
0.010046948400502409
0.028218694885361495
0.010271795295649977
Xfeature num_7 <----- best threshold 0 highest IG for this tree :  0.033572874300662525
 left:Xfeature num_5 <----- best threshold 0 highest IG for this tree :  0.02322951967884429
  left:Xfeature num_2 <----- best threshold 0 highest IG for this tree :  0.00013023255813962575
    left:0
    right:Xfeature num_1 <----- best threshold 0 highest IG for this tree :  5.2764183672039666e-05
        left:0
        right:0
  right:Xfeature num_4 <----- best threshold 0 highest IG for this tree :  0.017940038150619897
    left:Xfeature num_2 <----- best threshold 0 highest IG for this tree :  0.006513487976686272
        left:1
        right:0
    right:Xfeature num_3 <----- best threshold 0 highest IG for this tree :  0

In [52]:
Y_pred = classifier.predict(X_test) 
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, Y_pred)

0.75

In [53]:
Y_pred = classifier.predict(X_test_diab) 
from sklearn.metrics import accuracy_score
accuracy_score(Y_test_diab, Y_pred)

0.7272727272727273